### ISSUE TITLE
Plugin crashes after updating

### ISSUE THREAD

**Issue by beheist** [cvette/intellij-neos#16]
After updating to 0.1.14, the Plugin now crashes when I try to use code navigation features (e.g. cmd+clicking a Fusion prototype). There are two errors.

1.
```
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
```
Stacktrace:
```
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:623)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:522)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:504)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:105)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:836)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:776)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:821)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:892)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:199)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:196)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:219)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:623)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:522)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:504)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:105)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:836)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:776)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:821)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:892)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:199)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:196)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:219)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:623)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:522)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:504)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:105)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:836)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:776)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:821)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:892)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:199)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:196)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:219)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:312)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:892)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:569)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

2
```
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
```
Stacktrace:
```
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$1021/245062901.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by cvette** [comment]
This is a problem with version 2016.3 of intellij and is not reproducible in newer versions.
