### ISSUE TITLE
NullPointerException in ResolveEngine

### ISSUE THREAD

**Issue by fadorator** [cvette/intellij-neos#26]
Hi,

first of all: Thank you for this plugin, it makes working with Neos and Flow a lot better.

Sometimes however Idea reports a NullPointerException:

```
java.lang.NullPointerException
	at de.vette.idea.neos.lang.fusion.resolve.ResolveEngine.findPackagesDirectory(ResolveEngine.java:231)
	at de.vette.idea.neos.lang.fusion.resolve.ResolveEngine.findResource(ResolveEngine.java:197)
	at de.vette.idea.neos.lang.yaml.references.value.ValueReference.multiResolve(ValueReference.java:49)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:378)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:355)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:227)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:199)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I don't know a thing about Idea Plugins, but I guess ```currentFile.getName()``` might return null in some cases?

https://github.com/cvette/intellij-neos/blob/ca76d1239aac4c591e2f167f8ef86f13fa13d4d4/src/main/java/de/vette/idea/neos/lang/fusion/resolve/ResolveEngine.java#L231

This does not seem to be a big problem, since it seems like everything still works. I just wanted to let you know that there are people out there who use your plugin and appreciate the effort you are making!

Regards
Leif

**Comment by cvette** [comment]
Thanks for reporting this issue. 
It seems more likely that `currentFile` is null. Should be fixed with 422bc29. I'll create a release as soon as I have a few other things ready.
